# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazfull.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage, QPixmap
import imutils
import cv2
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 531)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/favicon_star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_image = QtWidgets.QLabel(self.frame_2)
        self.label_image.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_3.addWidget(self.label_image)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #00aaff;\n"
"    height: 4px;\n"
"    background: #00aaff;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(0, 170, 255);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    left: 11px;\n"
"    margin: -12px;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(0, 170, 255);\n"
"    font: 75 11pt \"MS Shell Dig 2\";\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.open_image = QtWidgets.QPushButton(self.frame_3)
        self.open_image.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.open_image.setObjectName("open_image")
        self.horizontalLayout_9.addWidget(self.open_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.slider_one = QtWidgets.QSlider(self.frame_3)
        self.slider_one.setMinimumSize(QtCore.QSize(0, 30))
        self.slider_one.setOrientation(QtCore.Qt.Horizontal)
        self.slider_one.setObjectName("slider_one")
        self.horizontalLayout_8.addWidget(self.slider_one)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.slider_two = QtWidgets.QSlider(self.frame_3)
        self.slider_two.setMinimumSize(QtCore.QSize(0, 30))
        self.slider_two.setOrientation(QtCore.Qt.Horizontal)
        self.slider_two.setObjectName("slider_two")
        self.horizontalLayout_7.addWidget(self.slider_two)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.slider_tree = QtWidgets.QSlider(self.frame_3)
        self.slider_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.slider_tree.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tree.setObjectName("slider_tree")
        self.horizontalLayout_6.addWidget(self.slider_tree)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slider_four = QtWidgets.QSlider(self.frame_3)
        self.slider_four.setMinimumSize(QtCore.QSize(0, 30))
        self.slider_four.setOrientation(QtCore.Qt.Horizontal)
        self.slider_four.setObjectName("slider_four")
        self.horizontalLayout_5.addWidget(self.slider_four)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.save_image = QtWidgets.QPushButton(self.frame_3)
        self.save_image.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.save_image.setObjectName("save_image")
        self.horizontalLayout_4.addWidget(self.save_image)
        self.reset_edit = QtWidgets.QPushButton(self.frame_3)
        self.reset_edit.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.reset_edit.setObjectName("reset_edit")
        self.horizontalLayout_4.addWidget(self.reset_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplicación con OpenCV"))
        self.open_image.setText(_translate("MainWindow", "Open Img"))
        self.label.setText(_translate("MainWindow", "H"))
        self.label_2.setText(_translate("MainWindow", "S"))
        self.label_3.setText(_translate("MainWindow", "V"))
        self.label_4.setText(_translate("MainWindow", "GRAY"))
        self.save_image.setText(_translate("MainWindow", "Save Img"))
        self.reset_edit.setText(_translate("MainWindow", "Reset Img"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
